language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

matrix:
  include:
    - perl: 5.30
      env: COVERAGE=1

before_install:
   - git config --global user.name "TravisCI"
   - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
   - source ~/travis-perl-helpers/init
   - build-perl
   - perl -V
   - cpanm -n Devel::Cover::Report::Coveralls
   - coverage-setup

install:
  - cpanm --quiet --notest Net::DNS@1.17 # for 5.8 travis builds
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - cpanm --notest Pod::Weaver::Section::GenerateSection Pod::Weaver::Section::Contributors
  - cpan-install --coverage

script:
   - dzil test

after_success:
  - coverage-report
