language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - eval $(curl https://travis-perl.github.io/init) --auto
  - coverage-setup
install:
  - cpanm --quiet --notest Net::DNS Net::DNS::Resolver::Mock # for 5.8 travis builds
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
after_success:
  - coverage-report
